[book]
language = "en"
multilingual = false
src = "docs"
title = "CONFIGURE-ME"

[build]
build-dir = "docs/book"

[preprocessor.paisano-preprocessor]
before = ["links"]
registry = ".#__std.init"

[[preprocessor.paisano-preprocessor.multi]]
cell = "repo"
chapter = "Cell: repo"
